###############################################################################################
name: Deploy Blog to GitHub Pages
###############################################################################################
# OVERVIEW OF THE WORKFLOW
# - Execute e2e test.
# - Main building process to make artifacts under /public dir.
# - Add verification file for Google Search Console(GSC) to track search performance.
# - Deploy Website to GitHub Pages. The artifacts under /public are pushed to gh-pages branch.
# - Submit Updated Sitemap to Google Search Console in order to index deployed page.
# - Check if the deployed website is accessible.
###############################################################################################

# WHEN TO RUN THIS WORKFLOW
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# WORKFLOW
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: npm install
        # Artifacts are made under /public dir.
        run: |
          yarn
      
      - name: Main building process
        # Artifacts are made under /public dir.
        run: |
          yarn build

      - name: Add verification file for Google Search Console(GSC)
        env:
          GSC_VERIFICATION_CODE: ${{ secrets.GSC_VERIFICATION_CODE}}
        run: |
          echo "google-site-verification: ${GSC_VERIFICATION_CODE}" > ./public/${GSC_VERIFICATION_CODE}

      - name: Add ads.txt
        env:
          GOOGLE_ADS_TXT: ${{ secrets.GOOGLE_ADS_TXT}}
        run: |
          echo "${GOOGLE_ADS_TXT}" > ./public/ads.txt 

      - name: Deploy Website to GitHub Pages
        env:
          GIT_SECRET: ${{ secrets.GIT_SECRET }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_ADDRESS: ${{ secrets.GIT_ADDRESS }}
        run: |
          git config --global user.email ${GIT_ADDRESS}
          git config --global user.name ${GIT_USERNAME}
          git remote set-url origin https://${GIT_USERNAME}:${GIT_SECRET}@github.com/kenchon/kenchon.github.io
          yarn deploy

      - name: Submit Updated Sitemap to Google Search Console
        env:
          WEBSITE_ENDPOINT: ${{ secrets.WEBSITE_ENDPOINT }}
        run: |
          curl https://www.google.com/ping?sitemap=${WEBSITE_ENDPOINT}

      - name: Check if the deployed website is accessible
        env:
          WEBSITE_ENDPOINT: ${{ secrets.WEBSITE_ENDPOINT }}
        run: |
          http_code=`curl -LI ${WEBSITE_ENDPOINT} -o /dev/null -w '%{http_code}\n' -s`
          if [ ${http_code} -ne 200 ]; then exit 1; fi
